RISCV = /nobackup/dp252572/riscv
CC = $(RISCV)/bin/riscv32-unknown-elf-gcc
OBJCP = $(RISCV)/bin/riscv32-unknown-elf-objcopy
OBJDUMP = $(RISCV)/bin/riscv32-unknown-elf-objdump
HEXDUMP = hexdump
LINK_FILE = ../link.ld 

IDIR = ../include
CC_FLAGS += -I$(IDIR) -nostdlib -nostartfiles -T $(LINK_FILE)
OBJCP_FLAGS += -j .text -j .eh_frame -j .shbss -j .rodata -j .data -j .sdata -O binary
OBJDUMP_FLAGS += -S
HEXDUMP_FLAGS += -v -e '1/8 "%08x\n"'

all: $(PROG) $(BINARY) $(MEM) $(DUMP)

$(PROG) : $(CSRC)
	$(CC) $(CC_FLAGS) -o $(PROG) $(CSRC)
$(BINARY) : $(PROG)
	$(OBJCP) $(OBJCP_FLAGS) $(PROG) $(BINARY)
$(MEM): $(BINARY)
	$(HEXDUMP) $(HEXDUMP_FLAGS) $(BINARY) > $(MEM)
$(DUMP) : $(PROG)
	$(OBJDUMP) $(OBJDUMP_FLAGS) $(PROG) > $(DUMP)

.PHONY: clean
clean:
	rm $(PROG) $(BINARY) $(MEM) $(DUMP)

