BASE = /nobackup/dp252572/rocc_prog_tests
RISCV = /nobackup/dp252572/riscv

ifndef ARCH_PREFIX
  ARCH_PREFIX = riscv32-unknown-elf
endif

CC = $(RISCV)/bin/$(ARCH_PREFIX)-gcc
OBJCP = $(RISCV)/bin/$(ARCH_PREFIX)-objcopy
OBJDUMP = $(RISCV)/bin/$(ARCH_PREFIX)-objdump
HEXDUMP = hexdump

ifndef LINK_FILE
  LINK_FILE = $(BASE)/link.ld 
endif

ifndef IDIR
  IDIR = $(BASE)/include
endif

CC_FLAGS += -static -I$(IDIR) -nostdlib -nostartfiles -T $(LINK_FILE) 
OBJCP_FLAGS += -j .text -j .eh_frame -j .shbss -j .rodata -j .data -j .sdata -O binary
OBJDUMP_FLAGS += -D
HEXDUMP_FLAGS += -v -e '1/8 "%08x\n"'

all: $(PROG) $(BINARY) $(MEM) $(DUMP)

$(PROG) : $(CSRC) $(LINK_FILE)
	$(CC) $(CC_FLAGS) -o $(PROG) $(CSRC)
$(BINARY) : $(PROG)
	$(OBJCP) $(OBJCP_FLAGS) $(PROG) $(BINARY)
$(MEM): $(BINARY)
	$(HEXDUMP) $(HEXDUMP_FLAGS) $(BINARY) > $(MEM)
$(DUMP) : $(PROG)
	$(OBJDUMP) $(OBJDUMP_FLAGS) $(PROG) > $(DUMP)

.PHONY: clean
clean:
	rm $(PROG) $(BINARY) $(MEM) $(DUMP)

