PROJECT = load_store_test
PROG = $(PROJECT).elf
BINARY = $(PROJECT).bin
DUMP = $(PROJECT).dump
MEM = $(PROJECT).mem

CSRC = main.c
IDIR = ../../include
CC_FLAGS = -O1
#LINK_FILE = link2.ld

include ../../Makefile.def
