PROJECT = rocc_blockcipher_test
PROG = $(PROJECT).elf
BINARY = $(PROJECT).bin
DUMP = $(PROJECT).dump
MEM = $(PROJECT).mem

CSRC = main.c rocc_blockcipher.c
IDIR = ./include -I../include
CC_FLAGS = -O1 
#CC_FLAGS += -fgnu89-inline

include ../Makefile.def
